### ISSUE TITLE
Does not work on Firefox

### ISSUE THREAD

**Issue by jdegger** [lookstudios/vue-loop#9]
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0`

No errors in the console

**Comment by jsmmth** [comment]
@jdegger I am currently working on some big improvements to mobile support, but this will be included too. Although I can't replicate the issue, would you mind being more specific with whats not working exactly, cause the looped scroll seems to work for me?

**Comment by jdegger** [comment]
Well, I'm not sure how to explain it better than 'it does not work'. I made a screencast for you so you can see it just works as normal static page without the infinite scrolling:

https://www.youtube.com/watch?v=0wB3N4jmvKA&feature=youtu.be

**Comment by jsmmth** [comment]
hmmmm. Am I missing something? https://www.dropbox.com/s/do586bks8nl4nmr/working%3F.mov?dl=0

**Comment by jdegger** [comment]
Restarting Firefox fixed the issue. No clue why, I even tried disabling some addons but just the restart seems sufficient.

Closing the issue :) nice work btw!

**Comment by qgustavor** [comment]
I think I have the same issue: scrolling [with the scroll wheel](https://directme.ga/view?!4FwRFKRI!798BNrOvFGkHgfAuVvL0tELSmuS-8ZVKXxNjACLtu7o "shamelessly promoting my side project") or [with the keyboard](https://directme.ga/view?!9dhX1L6L!sxRf4Mstgn8uOCRyS-LClzHS5jTYHADUk2rn-7KdCB8 "shamelessly promoting my side project") don't works until the page is resized. I don't know why, but it works if I scroll with mid button click or dragging the scroll bar.

I think the problem is that `getDimensions` get called before the cloned element gets included, so it's not counted in the `pageHeight` calculation, which makes `scrollHandler` behave as the page ended just before the cloned element. Resizing the page makes `getDimensions` run again, updating `pageHeight` to the correct value.
